######################################################################
# Automatically generated by qmake (3.0) Mon Jun 4 12:22:53 2018
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += . \
    /usr/local/include/opencv2 \
autotestserver/alsa_audio/audio_input.h \
           autotestserver/alsa_audio/ \
           autotestserver/audio_recog/ \
           autotestserver/pic_recog/ \
           autotestserver/testor/ \
           contribute/vad/ \
           contribute/pugixml/contrib/ \
           contribute/pugixml/src/
# Input
HEADERS += autotestserver/alsa_audio/audio_input.h \
           autotestserver/alsa_audio/audio_input_alsa.h \
           autotestserver/alsa_audio/audio_input_file.h \
           autotestserver/alsa_audio/audio_output_alsa.h \
           autotestserver/audio_recog/audio_process.h \
           autotestserver/audio_recog/Audio_Recog.h \
           autotestserver/audio_recog/ConfigAna.h \
           autotestserver/audio_recog/fingerprint.h \
           autotestserver/audio_recog/hash.h \
           autotestserver/audio_recog/recog.h \
           autotestserver/audio_recog/RecordButton_Define.h \
           autotestserver/audio_recog/vad.h \
           autotestserver/audio_recog/wav.h \
           autotestserver/audio_recog/WavFile.h \
           autotestserver/pic_recog/ExtractImageFromVideo.h \
           autotestserver/pic_recog/ExtractPointsFromImage.h \
           autotestserver/pic_recog/ImageRecogInfo.h \
           autotestserver/pic_recog/PicRecogProcess.h \
           autotestserver/pic_recog/RecogCharWithOCR.h \
           autotestserver/pic_recog/RectifyImages.h \
           autotestserver/testor/Action.h \
           autotestserver/testor/ActionComparePrompt.h \
#           autotestserver/testor/ActionJudgeBeepPlayed.h \
           autotestserver/testor/ActionJudgeBeep.h\
           autotestserver/testor/ActionJudgeTTSAndViewParallel.h \
           autotestserver/testor/ActionJudgeVrView.h \
           autotestserver/testor/ActionPlaying.h \
           autotestserver/testor/ActionVrControl.h \
           autotestserver/testor/Controler.h \
           autotestserver/testor/ExeclToXml.h \
           autotestserver/testor/sockcomm.h \
           autotestserver/testor/SocketServer.h \
           autotestserver/testor/TestCase.h \
           autotestserver/testor/TestCaseParser.h \
           contribute/vad/typedefs.h \
           contribute/vad/webrtc_vad.h \
           autotestserver/testor/socket/sockcomm.h \
           contribute/pugixml/contrib/foreach.hpp \
           contribute/pugixml/src/pugiconfig.hpp \
           contribute/pugixml/src/pugixml.hpp \
           autotestserver/testor/ActionJudgeBeepPrompt.h \
           autotestserver/testor/ActionJudgeBeepPromptBeep.h \
           autotestserver/testor/ActionJudgeEmptyRecordFile.h \
           autotestserver/testor/ActionJudgePromptBeep.h

SOURCES += autotestserver/main.cc \
           autotestserver/alsa_audio/audio_input_alsa.cc \
           autotestserver/alsa_audio/audio_input_file.cc \
           autotestserver/alsa_audio/audio_output_alsa.cc \
           autotestserver/alsa_audio/main.cc \
           autotestserver/audio_recog/audio_process.cpp \
           autotestserver/audio_recog/Audio_Recog.cpp \
           autotestserver/audio_recog/ConfigAna.cpp \
           autotestserver/audio_recog/fingerprint.cpp \
           autotestserver/audio_recog/hash.cpp \
           autotestserver/audio_recog/recog.cpp \
           autotestserver/audio_recog/vad.cpp \
           autotestserver/audio_recog/wav.cpp \
           autotestserver/audio_recog/WavFile.cpp \
           autotestserver/pic_recog/ExtractImageFromVideo.cpp \
           autotestserver/pic_recog/ExtractPointsFromImage.cpp \
           autotestserver/pic_recog/ImageRecogInfo.cpp \
           autotestserver/pic_recog/PicRecogProcess.cpp \
           autotestserver/pic_recog/RecogCharWithOCR.cpp \
           autotestserver/pic_recog/RectifyImages.cpp \
           autotestserver/testor/Action.cpp \
           autotestserver/testor/ActionComparePrompt.cpp \
#           autotestserver/testor/ActionJudgeBeepPlayed.cpp \
           autotestserver/testor/ActionJudgeBeep.cpp\
           autotestserver/testor/ActionJudgeTTSAndViewParallel.cpp \
           autotestserver/testor/ActionJudgeVrView.cpp \
           autotestserver/testor/ActionPlaying.cpp \
           autotestserver/testor/ActionVrControl.cpp \
           autotestserver/testor/Controler.cpp \
           autotestserver/testor/ExeclToXml.cpp \
           autotestserver/testor/SocketServer.cpp \
           autotestserver/testor/TestCase.cpp \
           autotestserver/testor/TestCaseParser.cpp \
           build/CMakeFiles/feature_tests.c \
           build/CMakeFiles/feature_tests.cxx \
           autotestserver/testor/socket/client.cpp \
           autotestserver/testor/socket/server.cpp \
           contribute/pugixml/src/pugixml.cpp \
           build/CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.c \
           build/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           contribute/pugixml/docs/samples/custom_memory_management.cpp \
           contribute/pugixml/docs/samples/include.cpp \
           contribute/pugixml/docs/samples/load_error_handling.cpp \
           contribute/pugixml/docs/samples/load_file.cpp \
           contribute/pugixml/docs/samples/load_memory.cpp \
           contribute/pugixml/docs/samples/load_options.cpp \
           contribute/pugixml/docs/samples/load_stream.cpp \
           contribute/pugixml/docs/samples/modify_add.cpp \
           contribute/pugixml/docs/samples/modify_base.cpp \
           contribute/pugixml/docs/samples/modify_remove.cpp \
           contribute/pugixml/docs/samples/save_custom_writer.cpp \
           contribute/pugixml/docs/samples/save_declaration.cpp \
           contribute/pugixml/docs/samples/save_file.cpp \
           contribute/pugixml/docs/samples/save_options.cpp \
           contribute/pugixml/docs/samples/save_stream.cpp \
           contribute/pugixml/docs/samples/save_subtree.cpp \
           contribute/pugixml/docs/samples/text.cpp \
           contribute/pugixml/docs/samples/traverse_base.cpp \
           contribute/pugixml/docs/samples/traverse_iter.cpp \
           contribute/pugixml/docs/samples/traverse_predicate.cpp \
           contribute/pugixml/docs/samples/traverse_rangefor.cpp \
           contribute/pugixml/docs/samples/traverse_walker.cpp \
           contribute/pugixml/docs/samples/xpath_error.cpp \
           contribute/pugixml/docs/samples/xpath_query.cpp \
           contribute/pugixml/docs/samples/xpath_select.cpp \
           contribute/pugixml/docs/samples/xpath_variables.cpp \
    autotestserver/testor/ActionJudgeBeepPrompt.cpp \
    autotestserver/testor/ActionJudgeBeepPromptBeep.cpp \
    autotestserver/testor/ActionJudgeEmptyRecordFile.cpp \
    autotestserver/testor/ActionJudgePromptBeep.cpp

DISTFILES += \
    CMakeLists.txt
